"""Seed the XAUUSD APEX strategy family into the StrategyVersion DB table
so the Apex bots appear in the Bots UI and can be backtested.

Run from `backend/`:

    uv run python -m scripts.seed_xauusd_apex_strategies
    uv run python -m scripts.seed_xauusd_apex_strategies --no-activate

Safely re-runnable: a family whose active version already has this exact
code hash is skipped rather than re-saved.

There is one strategy family per *entry timeframe*, because
`StrategySpec.entry_timeframe` is not something a skill's `param_overrides`
can reach — only params are overridable. Everything else that separates one
Apex bot from another (trendguard / turbo / precision) *is* a param, so those
bots share a family: `xauusd_apex_trendguard_m1`, `..._precision_m1` and
`..._turbo_m1` are all the M1 family with different overrides.

The M5/M15/H1/D1 files are exact-substitution copies of the M1 one — same
algorithm, shifted timeframe ladder, generated by
`scripts/gen_apex_timeframe_variants.py` into a fresh `_v{N}.py` file each
run (never overwriting an already-seeded version). Re-run this script after
generating a new one or the DB's active version silently goes stale against
the source — each *sibling* family's latest on-disk `_v{N}.py` file is what
gets hashed and considered, not a hardcoded version number.

The M1 family is deliberately excluded from that dynamic lookup and stays
pinned to `_v1`: M1 is edited and versioned through the normal versioning
API/UI (`StrategyVersionService.edit_code`, the AI refinement loop), not by
this script, so its on-disk "latest" file is whatever that flow last wrote,
which this script has no business re-seeding or activating. Resolving it
dynamically here once picked up a file that had drifted from what the DB's
`ACTIVE` row actually recorded and minted a spurious new version — the `_v1`
pin is intentional, not an oversight.

By default a family whose code changed gets saved as a new `VALIDATED`
version and then immediately activated, superseding whatever was live —
the behaviour the Bots UI / backtest-availability docstring above describes.
Pass `--no-activate` (or `seed(..., activate=False)`) to only register the
new code as `VALIDATED` and leave the currently active version running
untouched — use this for a sibling that hasn't been backtest-compared yet
and must not start trading live on its own.
"""

from __future__ import annotations

import argparse
import hashlib
import logging
import re
from pathlib import Path

from src.shared.config.settings import Settings
from src.shared.db.base import make_session_factory
from src.strategies.adapters.repository import StrategyVersionRepository
from src.strategies.application.versioning import StrategyVersionService
from src.strategies.domain.versioning import CodeSource
from src.strategies.registry import StrategyRegistry

logger = logging.getLogger(__name__)

_GENERATED_DIR = Path(__file__).resolve().parent.parent / "src" / "strategies" / "generated"

# M1 is pinned to its original seed file, not resolved dynamically — see the
# module docstring for why. The siblings resolve to whatever
# `gen_apex_timeframe_variants.py` most recently wrote.
_PINNED_STEMS: dict[str, str] = {
    "xauusd_snd_apex_trendguard_m1": "xauusd_snd_apex_trendguard_m1_v1",
}
_SIBLING_NAMES: tuple[str, ...] = tuple(
    f"xauusd_snd_apex_trendguard_{tf}" for tf in ("m5", "m15", "h1", "d1")
)
_NAMES: tuple[str, ...] = (*_PINNED_STEMS, *_SIBLING_NAMES)

_VERSION_RE = re.compile(r"_v(\d+)\.py$")


def _latest_file_stem(name: str) -> str:
    """The highest-numbered `{name}_v{N}.py` on disk for this family — the
    file `gen_apex_timeframe_variants.py` most recently wrote."""
    candidates = [
        (int(match.group(1)), path)
        for path in _GENERATED_DIR.glob(f"{name}_v*.py")
        if (match := _VERSION_RE.search(path.name))
    ]
    if not candidates:
        raise FileNotFoundError(f"no {name}_v*.py file found in {_GENERATED_DIR}")
    _, latest_path = max(candidates, key=lambda pair: pair[0])
    return latest_path.stem


def _file_stem(name: str) -> str:
    return _PINNED_STEMS[name] if name in _PINNED_STEMS else _latest_file_stem(name)


def seed(
    service: StrategyVersionService, repository: StrategyVersionRepository, *, activate: bool = True
) -> None:
    for name in _NAMES:
        file_stem = _file_stem(name)
        code = (_GENERATED_DIR / f"{file_stem}.py").read_text()
        code_hash = hashlib.sha256(code.encode()).hexdigest()
        existing = repository.list_all(name)
        if any(v.code_hash == code_hash for v in existing):
            logger.info("skipping %r — version with this exact code hash already in DB", name)
            continue
        version = service.save_generated_code(name=name, code=code, source=CodeSource.MANUAL)
        if activate:
            service.activate_version(version.id)
            logger.info(
                "seeded/activated %r (version=%d, id=%s)", name, version.version, version.id
            )
        else:
            logger.info(
                "seeded %r as VALIDATED, not activated (version=%d, id=%s)",
                name,
                version.version,
                version.id,
            )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-activate",
        action="store_true",
        help=(
            "register changed families as a new VALIDATED version without activating them, "
            "leaving whatever version is currently live untouched"
        ),
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    settings = Settings()
    session_factory = make_session_factory(settings.database_url)
    repository = StrategyVersionRepository(session_factory)
    service = StrategyVersionService(
        repository=repository, registry=StrategyRegistry(), generated_dir=_GENERATED_DIR
    )
    seed(service, repository, activate=not args.no_activate)


if __name__ == "__main__":
    main()
